Soundboard (audiosurf clone) (temporary name): cMonoMode Class Reference
cMonoMode Class Reference
#include <cMonoMode.h>
Public Member Functions
cMonoMode (const char *name)
virtual ~cMonoMode ()
int init ()
void drawship ()
void drawtrack ()
void CreatePickups ()
void changemonocolour ()
Detailed Description
Definition at line 8 of file cMonoMode.h.
Constructor & Destructor Documentation
cMonoMode::cMonoMode (const char * name)
Definition at line 3 of file cMonoMode.cpp.
cMonoMode::~cMonoMode () [virtual]
Definition at line 6 of file cMonoMode.cpp.
Member Function Documentation
int cMonoMode::init () [virtual]
Reimplemented from cPlayMode.
Definition at line 9 of file cMonoMode.cpp.
References bpm, cPlayMode::createpickup_thread, GAME_MODE, generate_pickups_thread(), InitMode(), RESET_MODE, score, and speed.
void cMonoMode::drawship () [virtual]
Reimplemented from cPlayMode.
Definition at line 17 of file cMonoMode.cpp.
References cShip::draw(), MONO_TRACK_WIDTH, cPlayMode::ship, and cShip::xpos.
void cMonoMode::drawtrack () [virtual]
Reimplemented from cPlayMode.
Definition at line 22 of file cMonoMode.cpp.
References changemonocolour(), c3DSModel::Draw(), dtime, speed, track, and cPlayMode::trackdisp.
void cMonoMode::CreatePickups () [virtual]
Reimplemented from cPlayMode.
Definition at line 39 of file cMonoMode.cpp.
References cPlayMode::addpickup(), cPlayMode::currentcolour, cPlayMode::currentposition, GenerateRandomNumber(), MONO, cPlayMode::newobjecttimer, cPlayMode::pickupcount, cPlayMode::quit_createpickup_thread, speed, and WHITE.
void cMonoMode::changemonocolour ()
Definition at line 73 of file cMonoMode.cpp.
References bpm, color, and MONO.
Referenced by drawtrack().
The documentation for this class was generated from the following files:
src/modes/cMonoMode.h
src/modes/cMonoMode.cpp