Soundboard (audiosurf clone) (temporary name): cPlayMode Class Reference
cPlayMode Class Reference
#include <cPlayMode.h>
Public Member Functions
cPlayMode (const char *name)
virtual ~cPlayMode ()
void add (iObject *object)
Add a generic object to the manager.
void addpickup (cPickup *pickup)
Add a pickup to the manager.
void addparticles (cParticleSystem *particles)
void update ()
Update objects controlled by the manager.
void draw ()
Draw objects controlled by the manager.
virtual void drawtrack ()
virtual void drawship ()
virtual void CreatePickups ()
string mainloop ()
virtual int init ()
string HandleEvents ()
Loops through waiting events, then takes keyboard state for arrow keys.
void Update ()
Updates game state.
void DrawScreen ()
Performs all the drawing functions.
void DrawText (char *text, int xpos, int ypos)
Public Attributes
Uint32 atime
player x-axis position from 0-1
cFont * font
GLfloat trackdisp
Uint32 newobjecttimer
int pickupcount
bool quit_createpickup_thread
SDL_Thread * createpickup_thread
cShip ship
list< iObject * > objectlist
List of all objects managed by cPlayMode.
list< cPickup * > pickuplist
List of pickups.
list< cParticleSystem * > particleslist
List of particle systems.
list< iObject * >::iterator it
Iterator for objectlist.
list< cPickup * >::iterator pt
Iterator for pickuplist.
list< cParticleSystem * >::iterator pst
Iterator for particleslist.
int currentcolour
The current pickup colour.
int currentposition
The current pickup (lane) position.
cPlayTable playtable
The playtable for the game.
int mode
Remove game objects; reset game essentially.
Detailed Description
Definition at line 18 of file cPlayMode.h.
Constructor & Destructor Documentation
cPlayMode::cPlayMode (const char * name)
Definition at line 3 of file cPlayMode.cpp.
References createpickup_thread, font, newobjecttimer, pickupcount, quit_createpickup_thread, ship, and trackdisp.
cPlayMode::~cPlayMode () [virtual]
Definition at line 14 of file cPlayMode.cpp.
References createpickup_thread, and quit_createpickup_thread.
Member Function Documentation
void cPlayMode::add (iObject * object)
Add a generic object to the manager.
Probably not used much outside of the class. Consider making private.
Definition at line 320 of file cPlayMode.cpp.
References objectlist.
void cPlayMode::addpickup (cPickup * pickup)
Add a pickup to the manager.
Definition at line 324 of file cPlayMode.cpp.
References pickuplist.
Referenced by CreatePickups(), cMonoMode::CreatePickups(), and Update().
void cPlayMode::addparticles (cParticleSystem * particles)
Definition at line 329 of file cPlayMode.cpp.
References particleslist.
void cPlayMode::update ()
Update objects controlled by the manager.
void cPlayMode::draw ()
Draw objects controlled by the manager.
void cPlayMode::drawtrack () [virtual]
Reimplemented in cMonoMode.
Definition at line 251 of file cPlayMode.cpp.
References c3DSModel::Draw(), dtime, speed, track, and trackdisp.
Referenced by DrawScreen().
void cPlayMode::drawship () [virtual]
Reimplemented in cMonoMode.
Definition at line 245 of file cPlayMode.cpp.
References cShip::draw(), NORMAL_TRACK_WIDTH, ship, and cShip::xpos.
Referenced by DrawScreen().
void cPlayMode::CreatePickups () [virtual]
Reimplemented in cMonoMode.
Definition at line 283 of file cPlayMode.cpp.
References addpickup(), currentcolour, currentposition, GenerateRandomNumber(), newobjecttimer, pickupcount, and quit_createpickup_thread.
Referenced by generate_pickups_thread().
string cPlayMode::mainloop () [virtual]
Implements iGameMode.
Definition at line 35 of file cPlayMode.cpp.
References atime, DrawScreen(), dtime, HandleEvents(), init(), and Update().
int cPlayMode::init () [virtual]
Reimplemented in cMonoMode, and cRandomMode.
Definition at line 20 of file cPlayMode.cpp.
References bpm, createpickup_thread, GAME_MODE, generate_pickups_thread(), InitMode(), objectlist, particleslist, pickuplist, playtable, RESET_MODE, score, and speed.
Referenced by mainloop().
string cPlayMode::HandleEvents ()
Loops through waiting events, then takes keyboard state for arrow keys.
Definition at line 66 of file cPlayMode.cpp.
References cShip::bank, dtime, iGameMode::event, SCREEN_WIDTH, ship, speed, and cShip::xpos.
Referenced by mainloop().
void cPlayMode::Update ()
Updates game state.
Definition at line 100 of file cPlayMode.cpp.
References AABBCollision3D(), addpickup(), c3DSModel::bbmax, c3DSModel::bbmin, block, cShip::bump(), cPlayTable::deletepickup(), DOWN, cPlayTable::getheight(), cPlayTable::height, it, cShip::model, iObject::modelviewmatrix, objectlist, pickuplist, playtable, cPlayTable::positions, pt, PT_FINE, PT_OVERFILL, cShip::respawn(), cShip::respawning, score, SCREEN_WIDTH, ship, cPlayTable::statuses, TransformPoint3fv(), cPlayTable::update(), cScore::update(), cShip::update(), WHITE, and cPlayTable::width.
Referenced by mainloop().
void cPlayMode::DrawScreen ()
Performs all the drawing functions.
Definition at line 203 of file cPlayMode.cpp.
References cPlayTable::draw(), drawship(), DrawText(), drawtrack(), font, cScore::get(), it, objectlist, playtable, score, SCREEN_HEIGHT, SCREEN_WIDTH, ship, cFont::string_width(), and cShip::xpos.
Referenced by mainloop().
void cPlayMode::DrawText (char * text, int xpos, int ypos)
Draws text on the screen.
Definition at line 262 of file cPlayMode.cpp.
References cFont::draw(), font, SCREEN_HEIGHT, and SCREEN_WIDTH.
Referenced by DrawScreen().
Member Data Documentation
Uint32 cPlayMode::atime
player x-axis position from 0-1
Definition at line 25 of file cPlayMode.h.
Referenced by mainloop().
cFont* cPlayMode::font
Definition at line 27 of file cPlayMode.h.
Referenced by cPlayMode(), DrawScreen(), and DrawText().
GLfloat cPlayMode::trackdisp
Definition at line 29 of file cPlayMode.h.
Referenced by cPlayMode(), drawtrack(), and cMonoMode::drawtrack().
Uint32 cPlayMode::newobjecttimer
Definition at line 30 of file cPlayMode.h.
Referenced by cPlayMode(), CreatePickups(), and cMonoMode::CreatePickups().
int cPlayMode::pickupcount
Definition at line 31 of file cPlayMode.h.
Referenced by cPlayMode(), CreatePickups(), and cMonoMode::CreatePickups().
bool cPlayMode::quit_createpickup_thread
Definition at line 32 of file cPlayMode.h.
Referenced by cPlayMode(), CreatePickups(), cMonoMode::CreatePickups(), and ~cPlayMode().
SDL_Thread* cPlayMode::createpickup_thread
Definition at line 33 of file cPlayMode.h.
Referenced by cPlayMode(), cRandomMode::init(), init(), cMonoMode::init(), and ~cPlayMode().
cShip cPlayMode::ship
Definition at line 35 of file cPlayMode.h.
Referenced by DrawScreen(), drawship(), cMonoMode::drawship(), HandleEvents(), and Update().
list< iObject* > cPlayMode::objectlist
List of all objects managed by cPlayMode.
This list doesn't contain the definitive pointer to any objects, but is useful when we want to loop through all objects - we won't have to make different loops for each object type.
Definition at line 44 of file cPlayMode.h.
Referenced by add(), DrawScreen(), init(), and Update().
list< cPickup* > cPlayMode::pickuplist
List of pickups.
This list has the definitive pointer for all pickups.
Definition at line 49 of file cPlayMode.h.
Referenced by addpickup(), init(), and Update().
list< cParticleSystem* > cPlayMode::particleslist
List of particle systems.
Definition at line 51 of file cPlayMode.h.
Referenced by addparticles(), and init().
list< iObject* >::iterator cPlayMode::it
Iterator for objectlist.
Definition at line 53 of file cPlayMode.h.
Referenced by DrawScreen(), and Update().
list< cPickup* >::iterator cPlayMode::pt
Iterator for pickuplist.
Definition at line 55 of file cPlayMode.h.
Referenced by Update().
list< cParticleSystem* >::iterator cPlayMode::pst
Iterator for particleslist.
Definition at line 57 of file cPlayMode.h.
int cPlayMode::currentcolour
The current pickup colour.
Used when generating rows of pickups.
Definition at line 63 of file cPlayMode.h.
Referenced by CreatePickups(), and cMonoMode::CreatePickups().
int cPlayMode::currentposition
The current pickup (lane) position.
Similar to currentcolour. Used when generating pickups.
Definition at line 68 of file cPlayMode.h.
Referenced by CreatePickups(), and cMonoMode::CreatePickups().
cPlayTable cPlayMode::playtable
The playtable for the game.
See cPlayTable docs for more details. The table is kept here as only one is needed, and it gets updated with everything else.
Definition at line 75 of file cPlayMode.h.
Referenced by DrawScreen(), init(), and Update().
int cPlayMode::mode
Remove game objects; reset game essentially.
Definition at line 93 of file cPlayMode.h.
The documentation for this class was generated from the following files:
src/modes/cPlayMode.h
src/modes/cPlayMode.cpp