Soundboard (audiosurf clone) (temporary name): cFont Class Reference
cFont Class Reference
Creates and renders a texture-mapped bitmap fixed-width font.
#include <cFont.h>
Public Member Functions
cFont (string file, int width, int height, string characters)
Default constructor.
void draw (string str)
Draw a string at the current coordinates.
void Test ()
Draw all characters at the current coordinates.
unsigned string_width (string)
Returns the width in pixels of the given string if using the current font.
Private Attributes
int char_width
Width of one block character in the font.
int char_height
Height of one block character in the font.
cTexture * texture
The texture handle for our font data.
string characters
the list of characters in this font.
Detailed Description
Creates and renders a texture-mapped bitmap fixed-width font.
Definition at line 16 of file cFont.h.
Constructor & Destructor Documentation
cFont::cFont (string file, int width, int height, string characters)
Default constructor.
Parameters:
file A string constant containing the path to the font file.
width The width of one character in pixels.
height The height of the font file / one character in pixels.
characters A string constant containing the list of characters in the font file.
Definition at line 3 of file cFont.cpp.
References char_height, char_width, and texture.
Member Function Documentation
void cFont::draw (string str)
Draw a string at the current coordinates.
Parameters:
str The characters to write.
x offset.
screen offset
Definition at line 14 of file cFont.cpp.
References cTexture::bind(), char_height, char_width, characters, and texture.
Referenced by cMenuItem::draw(), and cPlayMode::DrawText().
void cFont::Test ()
Draw all characters at the current coordinates.
Definition at line 50 of file cFont.cpp.
References cTexture::bind(), and texture.
unsigned cFont::string_width (string str)
Returns the width in pixels of the given string if using the current font.
Parameters:
str The string to measure
Definition at line 74 of file cFont.cpp.
References char_width.
Referenced by cPlayMode::DrawScreen().
Member Data Documentation
int cFont::char_width [private]
Width of one block character in the font.
Definition at line 44 of file cFont.h.
Referenced by cFont(), draw(), and string_width().
int cFont::char_height [private]
Height of one block character in the font.
Definition at line 46 of file cFont.h.
Referenced by cFont(), and draw().
cTexture* cFont::texture [private]
The texture handle for our font data.
Definition at line 48 of file cFont.h.
Referenced by cFont(), draw(), and Test().
string cFont::characters [private]
the list of characters in this font.
Definition at line 50 of file cFont.h.
Referenced by draw().
The documentation for this class was generated from the following files:
src/objects/cFont.h
src/objects/cFont.cpp