Soundboard (audiosurf clone) (temporary name): src/utils/utils.cpp File Reference
src/utils/utils.cpp File Reference
#include "utils.h"
Functions
SDL_Rect * CreateRect (int x, int y, int h, int w)
SDL_Color * CreateColour (Uint8 r, Uint8 g, Uint8 b)
SDL_Surface * SubSurface (SDL_Surface *sourcesurface, int x, int y, int width, int height)
void dump (SDL_Surface *x)
void PutPixel (SDL_Surface *surface, int x, int y, Uint32 pixel)
Uint32 GetPixel (SDL_Surface *surface, int x, int y)
GLfloat * TransformPointf (GLfloat *m, GLfloat *p)
GLfloat * TransformPoint3fv (GLfloat *m, GLfloat p[3])
void PrintMatrix (GLfloat *m)
Variables
Uint32 dtime
float deltatime
Function Documentation
SDL_Color* CreateColour (Uint8 r, Uint8 g, Uint8 b)
Definition at line 14 of file utils.cpp.
SDL_Rect* CreateRect (int x, int y, int h, int w)
Definition at line 7 of file utils.cpp.
Referenced by SubSurface().
void dump (SDL_Surface * x)
Definition at line 42 of file utils.cpp.
Uint32 GetPixel (SDL_Surface * surface, int x, int y)
Definition at line 88 of file utils.cpp.
void PrintMatrix (GLfloat * m)
Definition at line 147 of file utils.cpp.
void PutPixel (SDL_Surface * surface, int x, int y, Uint32 pixel)
Definition at line 52 of file utils.cpp.
SDL_Surface* SubSurface (SDL_Surface * sourcesurface, int x, int y, int width, int height)
Definition at line 20 of file utils.cpp.
References CreateRect().
Referenced by cAnimatedTexture::cAnimatedTexture().
GLfloat* TransformPoint3fv (GLfloat * m, GLfloat p[3])
Definition at line 127 of file utils.cpp.
References TransformPointf().
Referenced by cPlayMode::Update().
GLfloat* TransformPointf (GLfloat * m, GLfloat * p)
Definition at line 114 of file utils.cpp.
Referenced by TransformPoint3fv().
Variable Documentation
float deltatime
Definition at line 5 of file utils.cpp.
Uint32 dtime
Definition at line 4 of file utils.cpp.
Referenced by cPlayMode::drawtrack(), cMonoMode::drawtrack(), cPlayMode::HandleEvents(), Init(), cPlayMode::mainloop(), cShip::update(), cScorePickup::update(), cScore::update(), and cDownPickup::update().