Soundboard (audiosurf clone) (temporary name): cTexture Class Reference
cTexture Class Reference
A simple wrapper for texture functions.
#include <cTexture.h>
Public Member Functions
cTexture (string file)
Use SDL to load the texture from a file.
cTexture ()
Load a blank texture.
virtual ~cTexture ()
void bind ()
Bind the texture so that it will be used for drawing polygons.
Protected Member Functions
GLuint load_texture_from_surface (SDL_Surface *surface)
Utility function to load an SDL texture/surface from memory into an OpenGL texture.
Protected Attributes
GLuint texid
The texid that OpenGL gives us to work with.
Detailed Description
A simple wrapper for texture functions.
Later (or derivative) versions of this class will probably support multitexturing, animated textures etc.
Definition at line 16 of file cTexture.h.
Constructor & Destructor Documentation
cTexture::cTexture (string file)
Use SDL to load the texture from a file.
Definition at line 3 of file cTexture.cpp.
References load_texture_from_surface(), and texid.
cTexture::cTexture ()
Load a blank texture.
Definition at line 13 of file cTexture.cpp.
References texid.
cTexture::~cTexture () [virtual]
Definition at line 19 of file cTexture.cpp.
References texid.
Member Function Documentation
void cTexture::bind ()
Bind the texture so that it will be used for drawing polygons.
Reimplemented in cAnimatedTexture.
Definition at line 26 of file cTexture.cpp.
References texid.
Referenced by cTexturedParticle::draw(), cFont::draw(), and cFont::Test().
GLuint cTexture::load_texture_from_surface (SDL_Surface * surface) [protected]
Utility function to load an SDL texture/surface from memory into an OpenGL texture.
Definition at line 32 of file cTexture.cpp.
Referenced by cAnimatedTexture::cAnimatedTexture(), and cTexture().
Member Data Documentation
GLuint cTexture::texid [protected]
The texid that OpenGL gives us to work with.
Definition at line 31 of file cTexture.h.
Referenced by bind(), cTexture(), cAnimatedTexture::init(), and ~cTexture().
The documentation for this class was generated from the following files:
src/objects/cTexture.h
src/objects/cTexture.cpp