Soundboard (audiosurf clone) (temporary name): cMenuMode Class Reference
cMenuMode Class Reference
A basic menu mode.
#include <cMenuMode.h>
Public Member Functions
cMenuMode (string title, string name)
virtual ~cMenuMode ()
void additem (cMenuItem *)
void additem (string title, string target)
string mainloop ()
Protected Member Functions
void moveup ()
void movedown ()
string select ()
int loadmode (iGameMode *newmode)
string handleevents ()
void draw ()
void draw_cursor (unsigned x, unsigned y)
Protected Attributes
string title
vector< cMenuItem * > menuitems
vector< cMenuItem * >::iterator it
vector< cMenuItem * >::iterator currentitem
unsigned mousex
unsigned mousey
Detailed Description
A basic menu mode.
Displays a list of items, with target modes and titles for each.
We build a menu by first constructing a menu object and then calling additem() for each menu item we want, before calling init() then mainloop().
TODO: more transitions and stuff.
Definition at line 22 of file cMenuMode.h.
Constructor & Destructor Documentation
cMenuMode::cMenuMode (string title, string name)
Definition at line 3 of file cMenuMode.cpp.
References mousex, mousey, and iGameMode::parent.
cMenuMode::~cMenuMode () [virtual]
Definition at line 9 of file cMenuMode.cpp.
Member Function Documentation
void cMenuMode::additem (cMenuItem * tmpmenu)
Definition at line 19 of file cMenuMode.cpp.
References menuitems.
Referenced by main().
void cMenuMode::additem (string title, string target)
Definition at line 12 of file cMenuMode.cpp.
References menuitems.
string cMenuMode::mainloop () [virtual]
Implements iGameMode.
Definition at line 30 of file cMenuMode.cpp.
References currentitem, draw(), handleevents(), InitMode(), MENU_MODE, menuitems, and RESET_MODE.
void cMenuMode::moveup () [protected]
Definition at line 53 of file cMenuMode.cpp.
References currentitem, and menuitems.
Referenced by handleevents().
void cMenuMode::movedown () [protected]
Definition at line 62 of file cMenuMode.cpp.
References currentitem, and menuitems.
Referenced by handleevents().
string cMenuMode::select () [protected]
Definition at line 71 of file cMenuMode.cpp.
References draw().
Referenced by handleevents().
int cMenuMode::loadmode (iGameMode * newmode) [protected]
string cMenuMode::handleevents () [protected]
Definition at line 85 of file cMenuMode.cpp.
References iGameMode::event, mousex, mousey, movedown(), moveup(), iGameMode::parent, and select().
Referenced by mainloop().
void cMenuMode::draw () [protected]
Definition at line 119 of file cMenuMode.cpp.
References it, and menuitems.
Referenced by mainloop(), and select().
void cMenuMode::draw_cursor (unsigned x, unsigned y) [protected]
Definition at line 141 of file cMenuMode.cpp.
Member Data Documentation
string cMenuMode::title [protected]
Definition at line 34 of file cMenuMode.h.
vector< cMenuItem* > cMenuMode::menuitems [protected]
Definition at line 35 of file cMenuMode.h.
Referenced by additem(), draw(), mainloop(), movedown(), and moveup().
vector< cMenuItem* >::iterator cMenuMode::it [protected]
Definition at line 36 of file cMenuMode.h.
Referenced by draw().
vector< cMenuItem* >::iterator cMenuMode::currentitem [protected]
Definition at line 37 of file cMenuMode.h.
Referenced by mainloop(), movedown(), and moveup().
unsigned cMenuMode::mousex [protected]
Definition at line 48 of file cMenuMode.h.
Referenced by cMenuMode(), and handleevents().
unsigned cMenuMode::mousey [protected]
Definition at line 48 of file cMenuMode.h.
Referenced by cMenuMode(), and handleevents().
The documentation for this class was generated from the following files:
src/modes/cMenuMode.h
src/modes/cMenuMode.cpp