Soundboard (audiosurf clone) (temporary name): cPlayTable Class Reference
cPlayTable Class Reference
Controls the play table for a game.
#include <cPlayTable.h>
Public Member Functions
int addpickup (int lane, int type)
Add a pickup to the table, usually from a ship collision.
void deletepickup (int lane, int row)
Delete a certain pickup from the table.
void printtable ()
Prettyprint the table.
void update ()
Update the table.
void draw ()
Draw the table.
int getheight (int lane)
Get the height that a new pickup would drop into in the lane.
void dropcolumn (int lane)
Drop a column in case of an overfill.
cPlayTable (int width=3, int height=7)
Constructor.
virtual ~cPlayTable ()
int floodfill (vector< vector< cPlayNode * > > &grid, int l, int i, int targetcolour, bool considerlitnodes=false)
Public Attributes
int width
Table width (number of lanes/columns.
int height
Table height (number of rows).
vector< vector< cPlayNode * > > positions
Where table data is stored.
vector< int > statuses
Whether a lane has overfilled or not.
cAnimatedTexture * texture1
cAnimatedTexture * texture2
Detailed Description
Controls the play table for a game.
table properties: width is left to right and is first index on positions.
height is near to far and is the second index.
so positions[0][0] is the lowerleft corner and positions[width-1][height-1] is the upper right corner.
Definition at line 18 of file cPlayTable.h.
Constructor & Destructor Documentation
cPlayTable::cPlayTable (int width = 3, int height = 7)
Constructor.
The width and height currently have to be 3 and 7 since the game is not flexible enough yet for other values.
Definition at line 7 of file cPlayTable.cpp.
References height, positions, PT_FINE, statuses, texture1, texture2, and width.
cPlayTable::~cPlayTable () [virtual]
Definition at line 233 of file cPlayTable.cpp.
Member Function Documentation
int cPlayTable::addpickup (int lane, int type)
Add a pickup to the table, usually from a ship collision.
Parameters:
lane Which lane
type The colour/type of the pickup
Definition at line 55 of file cPlayTable.cpp.
References DEFAULT_COLOUR, dropcolumn(), floodfill(), getheight(), height, NONE, OVERFILL_PENALTY, positions, PT_FINE, PT_OVERFILL, score, statuses, WHITE, and width.
Referenced by cTPPickup::update().
void cPlayTable::deletepickup (int lane, int row)
Delete a certain pickup from the table.
Also shifts pickups above down.
Definition at line 99 of file cPlayTable.cpp.
References positions.
Referenced by cPlayMode::Update().
void cPlayTable::printtable ()
Prettyprint the table.
Definition at line 116 of file cPlayTable.cpp.
References height, positions, and width.
void cPlayTable::update ()
Update the table.
Definition at line 25 of file cPlayTable.cpp.
References floodfill(), height, positions, score, WHITE, and width.
Referenced by cPlayMode::Update().
void cPlayTable::draw ()
Draw the table.
Definition at line 126 of file cPlayTable.cpp.
References cAnimatedTexture::bind(), color, dlDrawQuad, height, positions, texture1, texture2, WHITE, and width.
Referenced by cPlayMode::DrawScreen().
int cPlayTable::getheight (int lane)
Get the height that a new pickup would drop into in the lane.
Parameters:
lane Which lane to use
Definition at line 167 of file cPlayTable.cpp.
References height, NONE, and positions.
Referenced by addpickup(), and cPlayMode::Update().
void cPlayTable::dropcolumn (int lane)
Drop a column in case of an overfill.
Definition at line 180 of file cPlayTable.cpp.
References height, and positions.
Referenced by addpickup().
int cPlayTable::floodfill (vector< vector< cPlayNode * > > & grid, int l, int i, int targetcolour, bool considerlitnodes = false)
Check for pickup groups using a flood fill algorithm.
Definition at line 208 of file cPlayTable.cpp.
References _floodfill(), DEFAULT_COLOUR, NONE, and WHITE.
Referenced by addpickup(), and update().
Member Data Documentation
int cPlayTable::width
Table width (number of lanes/columns.
Definition at line 21 of file cPlayTable.h.
Referenced by addpickup(), cPlayTable(), draw(), printtable(), update(), and cPlayMode::Update().
int cPlayTable::height
Table height (number of rows).
Definition at line 23 of file cPlayTable.h.
Referenced by addpickup(), cPlayTable(), draw(), dropcolumn(), getheight(), printtable(), update(), and cPlayMode::Update().
vector< vector<cPlayNode*> > cPlayTable::positions
Where table data is stored.
Definition at line 25 of file cPlayTable.h.
Referenced by addpickup(), cPlayTable(), deletepickup(), draw(), dropcolumn(), getheight(), printtable(), update(), and cPlayMode::Update().
vector< int > cPlayTable::statuses
Whether a lane has overfilled or not.
Definition at line 27 of file cPlayTable.h.
Referenced by addpickup(), cPlayTable(), and cPlayMode::Update().
cAnimatedTexture* cPlayTable::texture1
Definition at line 71 of file cPlayTable.h.
Referenced by cPlayTable(), and draw().
cAnimatedTexture* cPlayTable::texture2
Definition at line 72 of file cPlayTable.h.
Referenced by cPlayTable(), and draw().
The documentation for this class was generated from the following files:
src/objects/cPlayTable.h
src/objects/cPlayTable.cpp