Soundboard (audiosurf clone) (temporary name): src/modes/cPlayMode.cpp File Reference
src/modes/cPlayMode.cpp File Reference
#include "cPlayMode.h"
Functions
int generate_pickups_thread (void *playmode)
Function Documentation
int generate_pickups_thread (void * playmode)
Definition at line 314 of file cPlayMode.cpp.
References cPlayMode::CreatePickups().
Referenced by cRandomMode::init(), cPlayMode::init(), and cMonoMode::init().