Soundboard (audiosurf clone) (temporary name): src/modes/cPlayMode.h File Reference
src/modes/cPlayMode.h File Reference
#include "../utils/includes.h"
#include "iGameMode.h"
#include "../objects/cFont.h"
#include "../objects/iObject.h"
#include "../objects/cScorePickup.h"
#include "../objects/cDownPickup.h"
#include "../objects/cParticleSystem.h"
#include "../objects/cTPPickup.h"
#include "../objects/cShip.h"
#include <cmath>
Classes
class cPlayMode
Defines
#define NORMAL_TRACK_WIDTH 8
Functions
int generate_pickups_thread (void *a)
Variables
Uint32 dtime
c3DSModel * ship_model
c3DSModel * block
c3DSModel * track
GLuint dlDrawQuad
float speed
GLfloat shipmatrix [16]
GLuint bpm
Define Documentation
#define NORMAL_TRACK_WIDTH 8
Definition at line 16 of file cPlayMode.h.
Referenced by cPlayMode::drawship().
Function Documentation
int generate_pickups_thread (void * a)
Definition at line 314 of file cPlayMode.cpp.
References cPlayMode::CreatePickups().
Referenced by cRandomMode::init(), cPlayMode::init(), and cMonoMode::init().
Variable Documentation
c3DSModel* block
Definition at line 12 of file main.cpp.
GLuint bpm
Definition at line 8 of file main.cpp.
Referenced by cMonoMode::changemonocolour(), cRandomMode::init(), cPlayMode::init(), cMonoMode::init(), and Init().
GLuint dlDrawQuad
Definition at line 6 of file main.cpp.
Uint32 dtime
Definition at line 4 of file utils.cpp.
c3DSModel* ship_model
Definition at line 11 of file main.cpp.
GLfloat shipmatrix[16]
Definition at line 14 of file main.cpp.
float speed
Definition at line 7 of file main.cpp.
c3DSModel* track
Definition at line 13 of file main.cpp.
Referenced by cPlayMode::drawtrack(), and cMonoMode::drawtrack().