Soundboard (audiosurf clone) (temporary name): src/utils/includes.cpp File Reference
src/utils/includes.cpp File Reference
#include "includes.h"
Functions
unsigned long _rand (void)
unsigned GenerateRandomNumber (unsigned low, unsigned high)
bool InitMode (long long mode)
Set common GL variables to predetermined sets of values.
bool CheckErrors ()
Variables
GLfloat color [9][3][3]
GLfloat monocolor [3] = {1, 0, 0}
int DEFAULT_COLOUR = 0
Function Documentation
unsigned long _rand (void)
Definition at line 22 of file includes.cpp.
Referenced by GenerateRandomNumber().
bool CheckErrors ()
Definition at line 101 of file includes.cpp.
Referenced by InitGL(), and InitMode().
unsigned GenerateRandomNumber (unsigned low, unsigned high)
Generate a random integer between the two arguments.
Definition at line 36 of file includes.cpp.
References _rand().
Referenced by cPlayMode::CreatePickups(), and cMonoMode::CreatePickups().
bool InitMode (long long mode)
Set common GL variables to predetermined sets of values.
Will probably get added to with development - this is a good place to store some boilerplate code.
Parameters:
mode A bitmask determining what variables to set.
Definition at line 47 of file includes.cpp.
References CheckErrors(), GAME_MODE, InitMode(), MENU_MODE, NORMAL_PROJECTION, RESET_MODE, SCREEN_HEIGHT, and SCREEN_WIDTH.
Referenced by cRandomMode::init(), cPlayMode::init(), cMonoMode::init(), InitGL(), InitMode(), and cMenuMode::mainloop().
Variable Documentation
GLfloat color[9][3][3]
Initial value:
 { {{0.3, 0.3, 0.3},  {0, 0, 0},  {0, 0, 0}},
                                                   {{1, 0, 0},  {0.8, 0, 0},  {0.5, 0, 0}},
                               {{1, 1, 0},  {0.8, 0.8, 0},  {0.5, 0.5, 0}},
                               {{0, 1, 0},  {0, 0.8, 0},  {0, 0.5, 0}},
                               {{0, 0, 1},  {0, 0, 0.8},  {0, 0, 0.5}},
                               {{0.8, 0.1, 0.9},  {0.7, 0.075, 0.8},  {0.4, 0.05, 0.5}},
                               {{1, 1, 1},  {0.8, 0.8, 0.8}, {0.5, 0.5, 0.5}},
                               {{0, 0, 0},  {0, 0, 0},  {0, 0, 0}},
                               {{1, 0, 0},  {0.8, 0, 0},  {0.5, 0, 0}},
                                             }
Definition at line 4 of file includes.cpp.
Referenced by cMonoMode::changemonocolour(), cShip::draw(), cPlayTable::draw(), and cPickup::draw().
int DEFAULT_COLOUR = 0
Definition at line 17 of file includes.cpp.
Referenced by cPlayTable::addpickup(), and cPlayTable::floodfill().
GLfloat monocolor[3] = {1, 0, 0}
Definition at line 15 of file includes.cpp.