Soundboard (audiosurf clone) (temporary name): src/main.h File Reference
src/main.h File Reference
#include "utils/includes.h"
#include "SDL/SDL_image.h"
#include "objects/cFont.h"
#include "modes/cRandomMode.h"
#include "modes/cMenuMode.h"
#include "modes/cQuitMode.h"
#include "modes/cMonoMode.h"
#include "objects/cScore.h"
#include <cmath>
#include <string>
#include <cstdio>
#include <map>
Functions
bool Init ()
bool InitGL ()
Function Documentation
bool Init ()
Initialises game state.
Definition at line 70 of file main.cpp.
References bpm, dtime, InitGL(), SCREEN_BPP, SCREEN_HEIGHT, and SCREEN_WIDTH.
Referenced by main().
bool InitGL ()
Init tasks related to OpenGL. Called only by Init().
Definition at line 104 of file main.cpp.
References CheckErrors(), dlDrawQuad, InitMode(), and RESET_MODE.
Referenced by Init().